---
title: "DS 202 - lab #1: working with git and github"
author: "Yumou Qiu"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In-class practice #1



## Overview

In this activity you are going to learn how to collaborate using Github.  With your team members you will learn some basics which allow you to share and edit files on Github. 

1. Create a git repository hosted at GitHub
2. Build `README.md` file 
3. Commit changes to repository
3. Collaborate by forking and editing partners file
4. Explore Github features: insights, diff, blame, ect.


## Create a repository with a README.md file (10 minutes)

**Step 1**: First we are going to create a repository within our Github user account. 

Follow along with your instructor and perform these steps:

1. Go to your Github profile. The url should be [http://github/your-user-gitname]().
2. Create a new Github repository, click <span style="background:limegreen; color:white">new</span> button, under the repositories tab.
3. Name your repository `practice1-your-gitname`
4. In the details write "tips to working with git and github".
5. Click the initiate a `README.md file` option. 

## So far

-  Once the repository is created you will be directed to the repository page which now has its own web address. 
-  Each repository on Github has a unique url so you can easily share. 
-  The git history is a detailed history of all the changes made to that file.  One of the features of using Github is the ability to view your repository history which can be displayed in the Insights section of your Github repository page. 
-  At this point in the git history of your `practice1-your-gitname` repository there is only one commit.

## Edit the `README.md` file (5 minutes)

1.  Go to the `practice1-your-gitname` repository main page. Click on `README.md`, then click "edit this file". Add the following information into the `README.md` file:
    -  Name?
    -  What do you tell people about your field of study at a party?
    -  In the past month, what are the three main activities you have been doing at work/study?
    -  What are the three most important tools/strategies you use for organizing your work?

<p class="note">*tip*:  Notice that you can use markdown syntax. Use [this guide](https://help.github.com/articles/markdown-basics/) for Github's flavor of Markdown. Use the "Preview" button to view the formatting of your readme.md file. </p>

## Commit

- **Commit** takes a snap shot of your project. Each commit includes a commit message that concisely defines changes made or project state at the time of the commit. 

1. Summarize the changes that you have made in 50 characters or less and click the <span style="background:limegreen; color:white"> commit </span>    button. 
2. Check out the git history.  You should now see two commits.

<!---## Commit statements

Get into the habit of writing commit statements. They will help you later!

http://starlogs.net/#heike/rwrks

http://starlogs.net/#DS202-at-ISU/DS202-at-ISU.github.io
--->

# Edit and collaborate with your partner

## Collaborate 

Now it is time to collaborate with a partner.  Navigate to one of your team members' repository by searching the url directly in your github search windown (take a round-robin approach). In order to edit someone else's repository you usually follow this simplified work flow: 

1. Fork their repository to your user account 
2. Make edits and commit 
3. Create a pull request that merges your changes into their repository. 

<p class="note">*tip*: 
<!---Depending on the project there are variations on the above work flow. Often the rules for contributing to a project are outlined in a file called `CONTRIBUTING.md` within the repository. One of the more often used --->
See the works flows [Github Flow](https://guides.github.com/introduction/flow/). </p>

## Forking

- **Forking** is creating a copy of a git repository into your own account.  
-  Forking allows you to make changes to a repository without affecting the main repository of the project.  
-  This is one of the most exciting aspects of Github - you essentially encouraged to copy and play with anyone's code! 

## Forking

1.  To fork your partner's repository click the "fork" button in the top left hand part of your screen.  
2.  When it asks where you would like to fork the repository, choose your user account (if you are new to Github, this should be the only option).


## Make edits and commit

- You should now have a copy of your partners repository, `practice1-their-gitname`. 
-  Github keeps track of the entire git history of the project and all forked copies made of the project. 

1. Edit your partners repository by clicking the edit button.  
2.  Paste in the answers to your questions under theirs and make a commit. 

## Create a pull request

- A **pull request** is the final step in the collaboration process, essentially asking if the edits made to your copy can be incorporated into another repository. 

1.  Make sure you are in your copy of your partner's repository by looking at the url - your user name should preface the repository name.  
2.  Click the  <span style="background:limegreen; color:white">New Pull Request</span> button. You will get an overview of the changes you made to the repository. 
3.  Click the "Create a Pull Request" button to continue the pull request. Your partner will now get a notification of a pull request on their main repository, as will you if your partner made changes. 
4.  Go ahead and accept this pull request. 


## Explore Github Features

Now that you have accepted the pull request.  Take a few minutes to explore the git history using the Insights section of the repository. 

## Analyzing the "gapminder-5060" dataset

You may decide what you want to do. For example:

1. Creat a (R)Markdown file to study gdpPercap for US
2. You collaborator can add lines for different countries 


## Submission for homework 3

In Canvas, submit your (R) Markdown file with: 

  a. a table of team members, and their github repository links  
  b. the number of successful pull requests you made, and the github repository to which you requested a change 
  c. the number of pull requests you accepted, and the github repository from which you accepted
  b. a list with at least 3 tips of how to make working with git/github easier  
  e. make a pull request for your RMarkdown file for studying the US gdpPercap, the repository will be given in the homework.


## Note

make sure that none of the numbers in the above list are 0, i.e. each team member has to have at least one successful pull request made and accepted. Help out your team member in case they are stuck. 
